config/routes.rb
Xob::Application.routes.draw do

  devise_for :users

  resources :searches, only: [:new, :create] do
    collection do
      post :save_search
      get :get_draggables
    end
  end

  root :to => 'searches#new'

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
end

app/models/search.rb
require "./lib/google_custom_search_api.rb"

class Search < ActiveRecord::Base
  include GoogleCustomSearchApi

  belongs_to :user

  serialize :draggables, JSON

  after_initialize :set_services, :build_query_string

  attr_accessor :domain, :required_terms, :image, :add_terms, :file_type, :must_have,
    :excluded_terms, :exact_terms, :date_restrict, :google, :twitter, :services, :result_type, :google_query,
    :twitter_terms, :twitter_options

  def search
    {
      google_results: (GoogleCustomSearchApi.search(google_query) unless google_query.blank?),
      twitter_results: (Twitter.search(twitter_terms, twitter_options) unless twitter_terms.blank?)
    }
  end

  def save_search(json)
    self.draggables = json
    self.name = JSON.parse(json)["name"]
    save!
  end


  private

  def terms_to_query_string
    @required_terms = @required_terms.gsub(" ", "+") if @required_terms.present?
    @add_terms = @add_terms.gsub(" ", "+") if @add_terms.present?
    @must_have = @must_have.gsub(" ", "+") if @must_have.present?
    @excluded_terms = excluded_terms.gsub(" ", "+") if @excluded_terms.present?
    @exact_terms = exact_terms.gsub(" ", "+") if @exact_terms.present?
  end

  def set_services
    if google && twitter
      @services = [google, twitter]
    elsif google
      @services = [google]
    elsif twitter
      @services = [twitter]
    end
  end

  def build_query_string
    terms_to_query_string
    @google_query = ""
    @twitter_query = ""
    unless services.blank?
      @services.each do |service|
        if service == "twitter"
          @twitter_terms = ((required_terms if required_terms) || "")

          @twitter_options = {
            result_type: ((result_type if result_type) || "")
          }

        elsif service == "google"
          query_hash = {
            q: (("q=#{required_terms}" if required_terms) || ""),
            hq: (("&hq=#{add_terms}" if add_terms) || ""),
            siteSearch: (("&siteSearch=#{domain}" if domain) || ""),
            searchType: (("&searchType=#{image}" if image) || ""),
            fileType: (("&fileType=#{file_type}" if file_type) || ""),
            orTerms: (("&orTerms=#{must_have}" if must_have) || ""),
            excludeTerms: (("&excludeTerms=#{excluded_terms}" if excluded_terms) || ""),
            exactTerms: (("&exactTerms=#{exact_terms}" if exact_terms) || ""),
            dateRestrict: (("&dateRestrict=#{date_restrict}" if date_restrict) || "")
          }

          query_hash.each_pair do |k, v|
            @google_query << v
          end
        end
      end
    end
  end

  def image?
    @image ||= false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         # :token_authenticatable, :confirmable, :lockable,
         # :timeoutable, :omniauthable

  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    @user = current_user || User.new
  end

  def create
    @search = Search.new(search_params)
    @results = @search.search
  end

  def save_search
    @search ||= current_user.searches.new if current_user.present?
    @search.save_search(params[:draggables])
  end

  def get_draggables
    @draggables = current_user.searches.find(params[:id]).draggables
  end

  private

  def search_params
    params.require(:search).permit(:domain, :required_terms, :image, :add_terms,
      :file_type, :must_have, :excluded_terms, :exact_terms, :google,
      :twitter, :result_type, :draggables, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xob</title>
  <script id="loadarea" type="text/javascript"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="navbar-text pull-right">
  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/searches/_google_search_results.html.erb
<% if @results[:google_results] %>
  <table>
    <tr>
      <td>Title</td>
      <td>Link</td>
    </tr>

    <% @results[:google_results].items.each do |result| %>
      <tr>
        <td><%= result.htmlTitle.html_safe %></td>
        <td><%= link_to result.link, result.link %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Sorry, no results from google</p>
<% end %>

app/views/searches/_twitter_search_results.html.erb
<% if @results[:twitter_results] %>
  <table>
    <tr>
      <td>tweet</td>
    </tr>

    <% @results[:twitter_results].results.each do |result| %>
      <tr>
        <td><%= result.text %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Sorry, no results from Twitter</p>
<% end %>

app/views/searches/index.html.erb
<table>
  <tr>
    <td>Title</td>
    <td>Link</td>
  </tr>

  <% @results.items.each do |result| %>
    <tr>
      <td><%= result.title %></td>
      <td><%= link_to result.link, result.link %></td>
    </tr>
  <% end %>
</table>

<br /><br />
<%= @search.query %>

<%= @results %>

app/views/searches/new.html.erb
<div class="menuholder">
  <ul class="menu slide">
    <li><a href="http://www.script-tutorials.com/" class="red">Home</a></li>
    <li><a href="http://www.script-tutorials.com/" class="orange">Login/Sign Up</a>
      <div class="subs">
        <% if user_signed_in? %>
          <dl>
            <dt>Sign In</dt>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          </dl>
        <% else %>
          <dl>
            <dt>Sign In</dt>
            <%= form_for(@user, :url => session_path(@user)) do |f| %>
              <%= f.label :email %>
              <%= f.email_field :email, :autofocus => true %>

              <%= f.label :password %>
              <%= f.password_field :password %>

              <%= f.submit "Sign in" %>
            <% end %>

          </dl>
          <dl>
            <dt>Sign Up</dt>
            <%= form_for(@user, :url => registration_path(@user)) do |f| %>

              <div><%= f.label :email %>
              <%= f.email_field :email, :autofocus => true %></div>

              <div><%= f.label :password %>
              <%= f.password_field :password %></div>

              <div><%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation %></div>

              <div><%= f.submit "Sign up" %></div>
            <% end %>
          </dl>
        <% end %>
        <dl>
          <dt>Links #3</dt>
          <dd><a href="http://www.script-tutorials.com/category/html-css/">HTML / CSS</a></dd>
          <dd><a href="http://www.script-tutorials.com/category/jquery/">JS / jQuery</a></dd>
          <dd><a href="http://www.script-tutorials.com/category/php/">PHP</a></dd>
        </dl>
        <dl>
          <dt>Links #4</dt>
          <dd><a href="http://www.script-tutorials.com/category/mysql/">MySQL</a></dd>
          <dd><a href="http://www.script-tutorials.com/category/xslt/">XSLT</a></dd>
          <dd><a href="http://www.script-tutorials.com/category/ajax/">Ajax</a></dd>
        </dl>
      </div>
    </li>
    <li><a href="http://www.script-tutorials.com/category/resources/" class="yellow">Saved Searches</a>
        <div class="subs">
      <dl>
        <dt>Links #5</dt>
        <% @user.searches.each do |search| %>
          <dd><%= link_to search.name, get_draggables_searches_path(id: search.id), remote: true %></a></dd>
        <% end %>
      </dl>
      <dl>
        <dt>Links #6</dt>
        <dd><a href="http://www.script-tutorials.com/category/xslt/">XSLT</a></dd>
        <dd><a href="http://www.script-tutorials.com/category/ajax/">Ajax</a></dd>
      </dl>
      <dl>
        <dt>Links #7</dt>
        <dd><a href="http://www.script-tutorials.com/category/html-css/">HTML / CSS</a></dd>
        <dd><a href="http://www.script-tutorials.com/category/jquery/">JS / jQuery</a></dd>
      </dl>
      <dl>
        <dt>Links #8</dt>
        <dd><a href="http://www.script-tutorials.com/category/mysql/">MySQL</a></dd>
        <dd><a href="http://www.script-tutorials.com/category/ajax/">Ajax</a></dd>
      </dl>
    </div>
  </li>
  <li><a href="http://www.script-tutorials.com/category/resources/" class="green">Other</a></li>
  <li><a href="http://www.script-tutorials.com/about/" class="blue">About</a></li>
  <li><a href="http://www.script-tutorials.com/creating-css3-dropdown-menu-3/" class="violet">Back</a></li>
  </ul>
  <div class="back"></div>
  <div class="shadow"></div>
</div>

<div class="droppable" id="whole-page">

  <div id="header">

    <!-- <h1 id="logo">Scrolling Clouds</h1> -->

    <ul id="menu">
      <li><a id="home-link" href="#box1" class="link home selected">SEARCH</a></li>
      <li><a href="#box2" class="link results google">GOOGLE</a></li>
      <li><a href="#box3" class="link results twitter">TWITTER</a></li>
      <li><a href="#box4" class="link results bing">BING</a></li>
      <div id="nav-bar"><div id="slide"></div></div>
    </ul>
  </div>

  <div class="ui-draggable google down" id="google"><input class="expandable" name="search[google]" Value="google" size="10" type="hidden" READONLY></div>

  <div class="ui-draggable twitter down" id="twitter"><input class="expandable" name="search[twitter]" Value="twitter" size="10" type="hidden" READONLY></div>


  <div class="ui-draggable required_terms down"><input class="expandable" id="required_terms" name="search[required_terms]" placeholder="Terms" size="10" type="text"></div>

  <div class="ui-draggable domain down cloner"><input class="expandable" name="search[domain]" placeholder="Domain" size="10" type="text"></div>

  <div class="ui-draggable image down"><input class="expandable" name="search[image]" Value="image" size="10" type="text" READONLY></div>

  <div class="ui-draggable file_type down"><select class="expandable" id="search_file_type" name="search[file_type]">
    <option value="" disabled selected>File Type</option>
    <option value="pdf">pdf</option>
    <option value="doc">doc</option>
    <option value="xls">xls</option>
    <option value="txt">txt</option>
    <option value="rtf">rtf</option>
  </select></div>

  <div class="ui-draggable result_type down"><select class="expandable" id="search_result_type" name="search[result_type]">
    <option value="" disabled selected>Result Tpye</option>
    <option value="popular">Popular</option>
    <option value="recent">Recent</option>
    <option value="mixed">Mixed</option>
  </select></div>

  <div class='ui-draggable must_have down'><input class="expandable" name='search[must_have]' placeholder='Must Have'  size='10' type='text'></div>

  <div class='ui-draggable excluded_terms down'><input class="expandable" name='search[excluded_terms]' placeholder="Shouldnt Have"  size='10' type='text'></div>

  <div class='ui-draggable exact_terms down'><input class="expandable" name='search[exact_terms]' placeholder="Exact"  size='10' type='text'></div>

  <div class='ui-draggable date_restrict down'><input class="expandable" name='search[date_restrict]' placeholder="Date"  size='10' type='text'></div>

  <div id="wrapper">

    <ul id="mask">
      <li id="box1" class="box">
        <div id="google-drags">
        </div>
        <div id="twitter-drags">
        </div>
        <div id="trash">
        </div>
        <a name="box1"></a>
        <div class="content" id="search-box">
          <div class="inner droppable" id="box">
            <p>
              Home Box
            </p>
          </div>
        </div>
      </li>
      <li id="box2" class="box">
        <a name="box2"></a>
        <div class="content">
          <div id="inner-box-2" class="inner">
          Box 2
          </div>
        </div>
      </li>
      <li id="box3" class="box">
        <a name="box3"></a>
        <div class="content"><div id="inner-box-3" class="inner">Box 3</div></div>
      </li>
      <li id="box4" class="box">
        <a name="box4"></a>
        <div class="content"><div class="inner">Box 4</div></div>
      </li>
    </ul>
  </div>

<!--   <div id="cloud1" class="clouds">
    <div id="clouds-small"></div>
  </div>
  <div id="cloud2" class="clouds">
    <div id="clouds-big"></div>
  </div> -->

  <input name="search-name" placeholder="Search Name"  size='10' type="text" id="search-name">

  <a id="save-search">Save Search</a>

  <%= form_for @search, remote: true do |f| %>


    <%= f.submit id: "submit-button", value: "Search" %>

  <% end %>

</div>

app/views/searches/new1.html.erb
<div class="droppable" id="whole-page">
  <div class="droppable" id="box">

    <div class='ui-draggable terms'><input class="expandable" id='search_terms' name='search[terms]' placeholder='Terms' size='10' type='text'></div>

    <div class='ui-draggable domain'><input class="expandable" name='search[domain]' placeholder='Domain' size='10' type='text'></div>

    <div class='ui-draggable image'><input class="expandable" name='search[image]' Value='image' size='10' type='text' READONLY></div>

    <div class="ui-draggable file_type"><select class="expandable" id="search_file_type" name="search[file_type]">
      <option value="" disabled selected>File Type</option>
      <option value="pdf">pdf</option>
      <option value="doc">doc</option>
      <option value="xls">xls</option>
      <option value="txt">txt</option>
      <option value="rtf">rtf</option>
    </select></div>

    <div class='ui-draggable must_have'><input class="expandable" name='search[must_have]' placeholder='With This or That'  size='10' type='text'></div>

    <div class='ui-draggable excluded_terms'><input class="expandable" name='search[excluded_terms]' placeholder="Shouldnt Have"  size='10' type='text'></div>

    <div class='ui-draggable exact_terms'><input class="expandable" name='search[exact_terms]' placeholder="Exact"  size='10' type='text'></div>

    <p>Drop stuff in here!</p>

  </div>

  <div class="droppable" id="trash">Trash</div>

  <a id="add-terms" class="button" style="left: 215px; position: absolute;">Add Terms</a>



</div>